name: The very first workflow
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v6

      - name: List repo files
        run: ls -ltra

      - name: Executing all my shell script
        run: |
          chmod +x
          ./asc-script.sh
