name: The very first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v6
      - name: talk with today Bruhh
        run: echo "Hello world!"

      - name: list files
        run: ls

      - name: Read files
        run: cat README.md
