name: The very first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v6

      - name: List files and also read README.md
        run: |
          echo "Hello world!"  
          ls -ltra

      - name: Execute shell script
        run: ./asc-script.sh
